#!/usr/bin/python3
import sys

file_name = sys.argv[1]
with open(file_name, 'r') as f:
    for l in f:
        N = int(l.strip())
        if N % 2 == 0:
            print("{}={}*{}".format(N, 2, N//2))
        else:
            sqrt = int(N**0.5) + 1
            for i in range(3, sqrt, 2):
                if N % i == 0:
                    print("{}={}*{}".format(N, i, N//i))
                    break
